### ISSUE TITLE
Hello, sir

### ISSUE THREAD

**Issue by colinperepelken** [mackosx/dotfiles#1]
Hello, sir

I am looking for installation instructions. Can you help please? Also, would you consider please renaming Mackenzie.json to Colin.json? That would be great.

I appreciate your help.

Kind regards,

Cheers,

Colin Perepelken (formerly Colin Bernard)

**Comment by colinperepelken** [comment]
Hello, sir

I am eagerly awaiting your response.

Your friend,

"C"

**Comment by mackosx** [comment]
Hi Colin Perepelken (formerly Colin Bernard), simply run the `install.sh` script in your terminal (macOS only).
